#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGLightingZone
@end

@interface SWGLightingZone : SWGObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* name;

@property(nonatomic) NSNumber* deviceId;

@property(nonatomic) NSString* deviceType;

@property(nonatomic) NSString* zone;

@end
