#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SWGTemperatueZoneStatus
@end

@interface SWGTemperatueZoneStatus : SWGObject

/* the unique identifier for the zone 
 */
@property(nonatomic) NSString* _id;
/* the name of the zone [optional]
 */
@property(nonatomic) NSString* name;
/* the temperature in the zone 
 */
@property(nonatomic) NSNumber* value;
/* the temperature units [optional]
 */
@property(nonatomic) NSString* units;
/* the timestamp when the temperature was measured 
 */
@property(nonatomic) NSDate* timestamp;

@end
