#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SWGTemperatueZoneStatus.h"
#import "SWGTemperatureZone.h"


@protocol SWGTemperatureSummary
@end

@interface SWGTemperatureSummary : SWGObject


@property(nonatomic) NSArray<SWGTemperatureZone>* zones;

@property(nonatomic) NSArray<SWGTemperatueZoneStatus>* zoneStatus;

@end
