#import <Foundation/Foundation.h>
#import "SWGLightingSummary.h"
#import "SWGDeviceState.h"
#import "SWGApiResponse.h"
#import "SWGObject.h"
#import "SWGApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SWGZWaveApi: NSObject

@property(nonatomic, assign)SWGApiClient *apiClient;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SWGZWaveApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SWGZWaveApi*) sharedAPI;
///
///
/// 
/// 
///
/// 
///
/// @return SWGLightingSummary*
-(NSNumber*) getLightingSummaryWithCompletionHandler: 
    (void (^)(SWGLightingSummary* output, NSError* error)) handler;


///
///
/// 
/// 
///
/// @param deviceId 
/// 
///
/// @return SWGDeviceState*
-(NSNumber*) getSwitchStateWithDeviceId: (NSString*) deviceId
    completionHandler: (void (^)(SWGDeviceState* output, NSError* error)) handler;


///
///
/// 
/// 
///
/// @param deviceId 
/// @param value 
/// 
///
/// @return SWGApiResponse*
-(NSNumber*) setDimmerWithDeviceId: (NSString*) deviceId
    value: (NSNumber*) value
    completionHandler: (void (^)(SWGApiResponse* output, NSError* error)) handler;


///
///
/// 
/// sets a dimmer to a specific value on a timer
///
/// @param deviceId 
/// @param value 
/// @param minutes 
/// 
///
/// @return SWGApiResponse*
-(NSNumber*) setDimmerTimerWithDeviceId: (NSString*) deviceId
    value: (NSNumber*) value
    minutes: (NSNumber*) minutes
    completionHandler: (void (^)(SWGApiResponse* output, NSError* error)) handler;


///
///
/// 
/// 
///
/// @param deviceId 
/// @param value 
/// 
///
/// @return SWGApiResponse*
-(NSNumber*) setSwitchWithDeviceId: (NSString*) deviceId
    value: (NSString*) value
    completionHandler: (void (^)(SWGApiResponse* output, NSError* error)) handler;


///
///
/// 
/// sets a switch to a specific value on a timer
///
/// @param deviceId 
/// @param value 
/// @param minutes 
/// 
///
/// @return SWGApiResponse*
-(NSNumber*) setSwitchTimerWithDeviceId: (NSString*) deviceId
    value: (NSString*) value
    minutes: (NSNumber*) minutes
    completionHandler: (void (^)(SWGApiResponse* output, NSError* error)) handler;



@end
